# Generated by Django 3.2.21 on 2023-09-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resource_url',
            field=models.URLField(default='https://youtu.be/cBDzFf0wZqM?si=Cj-eqxexgr057IDY', max_length=100),
        ),
    ]
