# Generated by Django 3.2.21 on 2023-09-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('podcast', 'Podcast'), ('youtube_channel', 'YouTube Channel'), ('book_reading', 'Book/Reading')], default='normal', max_length=32),
        ),
    ]
