# Generated by Django 3.2.21 on 2023-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='country_filter',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('argentina', 'Argentina'), ('bolivia', 'Bolivia'), ('canary_islands', 'Canary Islands'), ('chile', 'Chile'), ('colombia', 'Colombia'), ('costa_rica', 'Costa Rica'), ('cuba', 'Cuba'), ('dominican_republic', 'Dominican Republic'), ('ecuador', 'Ecuador'), ('el_salvador', 'El Salvador'), ('equatorial_guinea', 'Equatorial Guinea'), ('guatemala', 'Guatemala'), ('honduras', 'Honduras'), ('mexico', 'Mexico'), ('nicaragua', 'Nicaragua'), ('panama', 'Panama'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('spain', 'Spain'), ('uruguay', 'Uruguay'), ('venezuela', 'Venezuela')], default='normal', max_length=32),
        ),
    ]
