# Generated by Django 3.2.21 on 2023-09-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20230907_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
