# Generated by Django 3.2.21 on 2023-09-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='link',
            new_name='resource_url',
        ),
    ]
