# Generated by Django 3.2.21 on 2023-09-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_rename_link_resource_resource_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image_filter',
        ),
    ]
